In [1]:
import numpy as np

In [2]:
my_list = [x * 10 for x in range(1, 11)]

my_array = np.array(my_list).reshape(5, 2)

my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [3]:
my_array.ndim

2

In [4]:
my_array.shape

(5, 2)

In [5]:
my_array.size

10

In [6]:
my_array.dtype

dtype('int32')

In [7]:
# Array Creation

In [8]:
my_array = np.arange(10, 101, 10).reshape(5, 2)

my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [9]:
# With linspace

my_array = np.linspace(10, 100, 10).reshape(5, 2)

my_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [10]:
# For fun: Use Array math to create multiples of 10 from single digit integers

my_array = (np.arange(1, 11) * 10).reshape(5, 2)

my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [11]:
rng = np.random.default_rng(2022)

random_array = rng.random(9).reshape(3, 3)

random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [12]:
# Accessing Array Data

In [13]:
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [14]:
random_array[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [15]:
random_array[2, 1]

0.04305584439252108

In [16]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

total = prices + 5

total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [17]:
discount_pct = random_array[:2, :].reshape(6)

pct_owed = 1 - discount_pct

final_owed = total * pct_owed

final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

In [18]:
((1 - (random_array[:2, :].reshape(6))) * total).round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

In [19]:
print(discount_pct)
print(pct_owed)
print(final_owed.round(2))

[0.24742606 0.09299006 0.61176337 0.06066207 0.66103343 0.75515778]
[0.75257394 0.90700994 0.38823663 0.93933793 0.33896657 0.24484222]
[ 8.27 10.88 10.67 98.62  3.39 13.46]


In [20]:
# Filtering Arrays

In [21]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [22]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [23]:
shipping = np.where(prices > 20, 0, 5)

shipping

array([5, 5, 0, 0, 5, 0])

In [24]:
# Aggregating and Sorting Arrays

In [25]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices.sort()

In [26]:
prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [27]:
top3 = prices[-3:]

In [28]:
top3

array([22.49, 49.99, 99.99])

In [29]:
print(f"Mean: {top3.mean()}")
print(f"Min: {top3.min()}")
print(f"Max: {top3.max()}")
print(f"Median: {np.median(top3)}")

Mean: 57.49
Min: 22.49
Max: 99.99
Median: 49.99


In [30]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [31]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

In [32]:
# Sales.csv

In [33]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    r"C:\Users\Zana\Desktop\pandas\retail\retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [34]:
produce_array = sales_array[family_array == "PRODUCE"]

In [35]:
rng = np.random.default_rng(2022)

random_array = rng.random(30)

sampled_array = produce_array[random_array < 0.5]

In [36]:
mean = sampled_array.mean()

mean

2268.102470588235

In [37]:
median = np.median(sampled_array)

median

1272.755

In [38]:
np.where(
    sampled_array < median,
    "below_both",
    np.where(sampled_array > mean, "above_both", "above_median"),
)

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')